### ISSUE TITLE
TrueVault Quick Start Guide link has changed

### ISSUE THREAD

**Issue by stepheneyer** [davidwoody/TrueVault-REST-API-for-Meteor#3]
Hi David - I'm starting a Meteor project using TrueVault and plan to use your package. I just noticed that the URL for the TrueVault Quick Start Guide has changed that you reference in the README. Here is the new URL:

https://www.truevault.com/quick-start-guide.html

Thanks!

**Comment by davidwoody** [comment]
@stepheneyer Thanks for letting me know! I've updated the README.
